const TeacherActionTypes = {
    FETCH_TEACHERS_START: 'FETCH_TEACHERS_START',
    FETCH_TEACHERS_SUCCESS: 'FETCH_TEACHERS_SUCCESS',
    FETCH_TEACHERS_FAILURE: 'FETCH_TEACHERS_FAILURE'
};

export default TeacherActionTypes;