const ObservationFormActionTypes = {
    SET_OBSERVATION_DETAILS: 'SET_OBSERVATION_DETAILS',
    SET_STANDARD_ONE: 'SET_STANDARD_ONE',
    SET_STANDARD_TWO: 'SET_STANDARD_TWO',
    SET_STANDARD_THREE: 'SET_STANDARD_THREE',
    SET_STANDARD_FOUR: 'SET_STANDARD_FOUR',
    SET_OBSERVATION_NOTES: 'SET_OBSERVATION_NOTES',
    RESET_FORM: 'RESET_FORM'
};

export default ObservationFormActionTypes;