const SavedObservationsActionTypes = {
    FETCH_SAVED_OBSERVATIONS_START: 'FETCH_SAVED_OBSERVATIONS_START',
    FETCH_SAVED_OBSERVATIONS_SUCCESS: 'FETCH_SAVED_OBSERVATIONS_SUCCESS',
    FETCH_SAVED_OBSERVATIONS_FAIL: 'FETCH_SAVED_OBSERVATIONS_FAIL',
    RESET_SAVED_OBSERVATIONS: 'RESET_SAVED_OBSERVATIONS'
};

export default SavedObservationsActionTypes;